sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: BzVS0+jv89J26P2g2SRJJVBCVy188tdff7OjGZwWPyqL5aWQtPtX0i5TLpvocRUA5RWve5NB/SdjRHE+CoUF6D+K2k8oDyXmao3G/Ovg3Q5bibeN6NesRyYr2xolNimHb0qB0jEiZny0p/JEfcR0Tv+N0J/Rm/zIqnvgNkLvQ1m/tv8GEW/PLQ8UsnPpetHnEyOve5FbgSHi8Bq67grSFtyIWPFPe4QpCtESU9QrB3d6XYpVp3CI4+T+jbJZFVpHqRswxunfP/QWWOIBWiY8iIFaXonHnAWuMmBg5UsFu1pqmo8SNSDWnhlmku9iyDgj2/6135SNWtgepUFmuQ8lRcDBmgrVRroep8/9SsGkePDsoyJy9tc2g2JnwojkyUbRyFOxjEKBb66cT5sfn4VrmHxBsMm3DhFBgMvPXwfNtLLpczeK+iRh63ZJHG6Vny9RhgC705owbiDTUO9fY+6n85rAQanscs3I0M0YmIlAHyxcH28XaOjoRNyRRxQL1LbmTuZJ0e09FTHP5IBh37K+f8M0cbmVpWd83HyLRlHBd9frfvvtAoaPMrT6G855zfdDrI122HEQ5SgNg5Q+DkfEgeefZDH6qVyCGzYZPegI0/rRhlwi083lsVJoGGEk+DFn0NgRCBMXOfFvdiqqEjRZbPNGEonkHp0YxNwc1IOmNEo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/No-Thoroughfare_1423
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy